name: cevelop
base: core18
adopt-info: scrape-download
summary: The C++ IDE for professional developers
description: |
  Major parts of Cevelop are Open Source as Eclipse CDT to which we actively
  contribute, especially in the area of the C++ parser and refactoring
  infrastructure.
grade: stable
confinement: classic

architectures:
  - build-on: amd64

parts:
  scrape-download:
    plugin: nil
    override-pull: |
      CEVELOP_VERSION=$(curl -s https://www.cevelop.com/download/ | sed -n 's!^.*href="/cevelop/downloads/cevelop-\([0-9.-]*\)-linux.gtk.x86_64.tar.gz.*!\1!p' -)
      snapcraftctl set-version $CEVELOP_VERSION
      curl -s -o $SNAPCRAFT_PART_INSTALL/cevelop-linux.gtk.x86_64.tar.gz https://www.cevelop.com/cevelop/downloads/cevelop-$CEVELOP_VERSION-linux.gtk.x86_64.tar.gz
      snapcraftctl pull
    prime:
      - -cevelop-linux.gtk.x86_64.tar.gz

  cevelop:
    after: [scrape-download]
    plugin: dump
    source: $SNAPCRAFT_STAGE/cevelop-linux.gtk.x86_64.tar.gz

  java:
    plugin: nil
    stage-packages:
      - openjdk-11-jre
    prime:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts

environment:
  PATH: $PATH:/snap/cevelop/current/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH/bin/

apps:
  cevelop:
    command: bash -c "env XDG_RUNTIME_DIR=/run/user/$(id -u) $SNAP/cevelop.sh -configuration $SNAP_USER_DATA/.cevelop"
    desktop: cevelop.desktop
