name: cevelop
base: core18
adopt-info: scrape-download
summary: The C++ IDE for professional developers
description: |
  Major parts of Cevelop are Open Source as Eclipse CDT to which we actively
  contribute, especially in the area of the C++ parser and refactoring
  infrastructure.
grade: stable
confinement: classic

architectures:
  - build-on: amd64

parts:
  scrape-download:
    plugin: nil
    override-pull: |
      sudo apt install --assume-yes curl
      CEVELOP_VERSION=$(curl -s https://www.cevelop.com/download/ | sed -n 's!^.*href="/cevelop/downloads/cevelop-\([0-9.-]*\)-linux.gtk.x86_64.tar.gz.*!\1!p' -)
      snapcraftctl set-version $CEVELOP_VERSION
      curl -s -o $SNAPCRAFT_PART_INSTALL/cevelop-linux.gtk.x86_64.tar.gz https://www.cevelop.com/cevelop/downloads/cevelop-$CEVELOP_VERSION-linux.gtk.x86_64.tar.gz
      snapcraftctl pull
    prime:
      - -cevelop-linux.gtk.x86_64.tar.gz

  cevelop:
    after: [scrape-download, dependencies]
    plugin: dump
    source: $SNAPCRAFT_STAGE/cevelop-linux.gtk.x86_64.tar.gz

  # This might be overkill, it comes from scraping a --strace of a failing run on 20.04
  # and adding a package for every file that was opened from the host filesystem.
  dependencies:
    plugin: nil
    stage-packages:
      - libatk1.0-0
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libcairo2
      - libcairo-gobject2
      - libdatrie1
      - libepoxy0
      - libffi6
      - libfontconfig1
      - libfreetype6
      - libfribidi0
      - libgdk-pixbuf2.0-0
      - libglib2.0-0
      - libgraphite2-3
      - libgtk-3-0
      - libharfbuzz0b
      - liblz4-1
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libpangoft2-1.0-0
      - libpcre2-8-0
      - libpixman-1-0
      - libpng16-16
      - libthai0
      - libwayland-client0
      - libwayland-cursor0
      - libwayland-egl1
      - libx11-6
      - libxau6
      - libxcb1
      - libxcb-render0
      - libxcb-shm0
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxkbcommon0
      - libxrandr2
      - libxrender1

  java:
    plugin: nil
    stage-packages:
      - openjdk-11-jre
    prime:
      - -usr/lib/jvm/java-11-openjdk-amd64/lib/security/cacerts

environment:
  PATH: $PATH:/snap/cevelop/current/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH/bin/
  JAVA_HOME: /snap/cevelop/current/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH/
  # Unfortunately, adding LD_LIBRARY_PATH, might break launching code under development
  LD_LIBRARY_PATH: /snap/cevelop/current/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/

apps:
  cevelop:
    command: bash -c "env XDG_RUNTIME_DIR=/run/user/$(id -u) $SNAP/cevelop.sh -configuration $SNAP_USER_DATA/.cevelop"
    desktop: cevelop.desktop
