name: cevelop
base: core18
adopt-info: cevelop
summary: The C++ IDE for professional developers
description: |
  Major parts of Cevelop are Open Source as Eclipse CDT to which we actively
  contribute, especially in the area of the C++ parser and refactoring
  infrastructure.
grade: stable
confinement: classic

parts:
  cevelop:
    plugin: dump
    # Source ought to be some "current" download, maybe we can add a sig check?
    source: https://www.cevelop.com/cevelop/downloads/cevelop-1.11.1-201902151304-linux.gtk.x86_64.tar.gz
    override-build: |
      snapcraftctl build
      # I'm guessing where to extract the best version.
      snapcraftctl set-version $(ls $SNAPCRAFT_PART_INSTALL/plugins/com.cevelop.ide.branding*.jar | sed -rne 's/^[^0-9]*([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*).+$/\1/p')

  java:
    plugin: nil
    stage-packages:
      - openjdk-11-jre
    override-build: |
      snapcraftctl build
      rm $SNAPCRAFT_PART_INSTALL/usr/lib/jvm/java-11-openjdk-*/lib/security/cacerts

environment:
  PATH: $PATH:/snap/cevelop/current/usr/lib/jvm/java-11-openjdk-$SNAP_ARCH/bin/

apps:
  cevelop:
    command: bash -c "env XDG_RUNTIME_DIR=/run/user/$(id -u) $SNAP/cevelop.sh -configuration $SNAP_USER_DATA/.cevelop"
